from typing import Protocol, Optional
from .entities import TelegramUser

class TelegramUserRepo(Protocol):
    async def get(self, telegram_id: int) -> Optional[TelegramUser]: ...
    async def upsert(self, user: TelegramUser) -> TelegramUser: ...
    async def update_state(self, telegram_id: int, state: str, temp_data: dict) -> None: ...

class TelegramNotifier(Protocol):
    async def send_message(self, chat_id: int, text: str, parse_mode: str = "Markdown") -> bool: ...
