"""add_debt_tracking_model

Revision ID: 190152f740ce
Revises: c69b561689a0
Create Date: 2026-01-22 20:39:38.616170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190152f740ce'
down_revision: Union[str, Sequence[str], None] = 'c69b561689a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trs_debt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creditor_user_id', sa.BigInteger(), nullable=False, comment='User yang bayar duluan (punya piutang)'),
    sa.Column('debtor_user_id', sa.BigInteger(), nullable=False, comment='User yang ngutang (punya hutang)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | paid | cancelled'),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True, comment='Transaction ID jika ada pembayaran via transfer'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','paid','cancelled')", name='ck_debt_status'),
    sa.CheckConstraint('amount > 0', name='ck_debt_amount_positive'),
    sa.ForeignKeyConstraint(['creditor_user_id'], ['sys_telegram_user.id'], ),
    sa.ForeignKeyConstraint(['debtor_user_id'], ['sys_telegram_user.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['trs_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debt_creditor_status', 'trs_debt', ['creditor_user_id', 'status'], unique=False)
    op.create_index('idx_debt_debtor_status', 'trs_debt', ['debtor_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_trs_debt_creditor_user_id'), 'trs_debt', ['creditor_user_id'], unique=False)
    op.create_index(op.f('ix_trs_debt_debtor_user_id'), 'trs_debt', ['debtor_user_id'], unique=False)
    op.drop_column('trs_transaction', 'embedding_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trs_transaction', sa.Column('embedding_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trs_debt_debtor_user_id'), table_name='trs_debt')
    op.drop_index(op.f('ix_trs_debt_creditor_user_id'), table_name='trs_debt')
    op.drop_index('idx_debt_debtor_status', table_name='trs_debt')
    op.drop_index('idx_debt_creditor_status', table_name='trs_debt')
    op.drop_table('trs_debt')
    # ### end Alembic commands ###
