"""Initial tables

Revision ID: 2ed1bfb43f61
Revises: 
Create Date: 2026-01-19 12:26:09.920169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ed1bfb43f61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_telegram_user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('temp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('income','expense')", name='ck_category_type'),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_telegram_user_id', 'name', 'type', name='uq_cat_user_name_type')
    )
    op.create_index(op.f('ix_mst_category_owner_telegram_user_id'), 'mst_category', ['owner_telegram_user_id'], unique=False)
    op.create_table('mst_wallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_telegram_user_id', 'name', name='uq_wallet_user_name')
    )
    op.create_index(op.f('ix_mst_wallet_owner_telegram_user_id'), 'mst_wallet', ['owner_telegram_user_id'], unique=False)
    op.create_table('trs_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('target_wallet_id', sa.Integer(), nullable=True),
    sa.Column('trx_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('embedding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('income','expense','transfer')", name='ck_trx_type'),
    sa.ForeignKeyConstraint(['category_id'], ['mst_category.id'], ),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.ForeignKeyConstraint(['target_wallet_id'], ['mst_wallet.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['mst_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trx_owner_date', 'trs_transaction', ['owner_telegram_user_id', 'trx_date'], unique=False)
    op.create_index(op.f('ix_trs_transaction_owner_telegram_user_id'), 'trs_transaction', ['owner_telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trs_transaction_owner_telegram_user_id'), table_name='trs_transaction')
    op.drop_index('idx_trx_owner_date', table_name='trs_transaction')
    op.drop_table('trs_transaction')
    op.drop_index(op.f('ix_mst_wallet_owner_telegram_user_id'), table_name='mst_wallet')
    op.drop_table('mst_wallet')
    op.drop_index(op.f('ix_mst_category_owner_telegram_user_id'), table_name='mst_category')
    op.drop_table('mst_category')
    op.drop_table('sys_telegram_user')
    # ### end Alembic commands ###
