"""membership

Revision ID: e13d2a67902a
Revises: 9b2d4f6a8c11
Create Date: 2026-07-05 12:27:59.680330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13d2a67902a'
down_revision: Union[str, Sequence[str], None] = '9b2d4f6a8c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbr_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbr_plan_code'), 'mbr_plan', ['code'], unique=True)
    op.create_table('mbr_payment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['mbr_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbr_payment_owner_telegram_user_id'), 'mbr_payment', ['owner_telegram_user_id'], unique=False)
    op.create_index(op.f('ix_mbr_payment_plan_id'), 'mbr_payment', ['plan_id'], unique=False)
    op.create_index(op.f('ix_mbr_payment_provider_reference'), 'mbr_payment', ['provider_reference'], unique=True)
    op.create_index(op.f('ix_mbr_payment_status'), 'mbr_payment', ['status'], unique=False)
    op.create_table('mbr_plan_feature',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('limit_period', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['mbr_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_key', name='uq_plan_feature')
    )
    op.create_index(op.f('ix_mbr_plan_feature_feature_key'), 'mbr_plan_feature', ['feature_key'], unique=False)
    op.create_index(op.f('ix_mbr_plan_feature_plan_id'), 'mbr_plan_feature', ['plan_id'], unique=False)
    op.create_table('mbr_subscription',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['mbr_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbr_subscription_owner_telegram_user_id'), 'mbr_subscription', ['owner_telegram_user_id'], unique=False)
    op.create_index(op.f('ix_mbr_subscription_plan_id'), 'mbr_subscription', ['plan_id'], unique=False)
    op.create_index(op.f('ix_mbr_subscription_status'), 'mbr_subscription', ['status'], unique=False)
    op.create_table('mbr_usage_counter',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_telegram_user_id'], ['sys_telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_telegram_user_id', 'feature_key', 'period_start', 'period_end', name='uq_usage_counter_period')
    )
    op.create_index(op.f('ix_mbr_usage_counter_feature_key'), 'mbr_usage_counter', ['feature_key'], unique=False)
    op.create_index(op.f('ix_mbr_usage_counter_owner_telegram_user_id'), 'mbr_usage_counter', ['owner_telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mbr_usage_counter_owner_telegram_user_id'), table_name='mbr_usage_counter')
    op.drop_index(op.f('ix_mbr_usage_counter_feature_key'), table_name='mbr_usage_counter')
    op.drop_table('mbr_usage_counter')
    op.drop_index(op.f('ix_mbr_subscription_status'), table_name='mbr_subscription')
    op.drop_index(op.f('ix_mbr_subscription_plan_id'), table_name='mbr_subscription')
    op.drop_index(op.f('ix_mbr_subscription_owner_telegram_user_id'), table_name='mbr_subscription')
    op.drop_table('mbr_subscription')
    op.drop_index(op.f('ix_mbr_plan_feature_plan_id'), table_name='mbr_plan_feature')
    op.drop_index(op.f('ix_mbr_plan_feature_feature_key'), table_name='mbr_plan_feature')
    op.drop_table('mbr_plan_feature')
    op.drop_index(op.f('ix_mbr_payment_status'), table_name='mbr_payment')
    op.drop_index(op.f('ix_mbr_payment_provider_reference'), table_name='mbr_payment')
    op.drop_index(op.f('ix_mbr_payment_plan_id'), table_name='mbr_payment')
    op.drop_index(op.f('ix_mbr_payment_owner_telegram_user_id'), table_name='mbr_payment')
    op.drop_table('mbr_payment')
    op.drop_index(op.f('ix_mbr_plan_code'), table_name='mbr_plan')
    op.drop_table('mbr_plan')
    # ### end Alembic commands ###
