from typing import Protocol, Optional, List
from datetime import date
from app.infrastructure.db.models import MstWallet, MstCategory, TrsTransaction, TrsDebt, SysTelegramUser

class FinanceRepoPort(Protocol):
    async def get_wallet_by_name(self, user_id: int, name: str) -> Optional[MstWallet]: ...
    async def create_wallet(self, user_id: int, name: str, initial_balance: float = 0) -> MstWallet: ...
    async def get_wallet_balance(self, wallet_id: int, user_id: int) -> float: ...

    async def get_category_by_name(self, user_id: int, name: str, type: str) -> Optional[MstCategory]: ...
    async def create_category(self, user_id: int, name: str, type: str) -> MstCategory: ...

    async def find_user_by_name_or_username(self, query: str) -> Optional[SysTelegramUser]: ...

    async def create_transaction(
        self,
        user_id: int,
        wallet_id: int,
        amount: float,
        type: str,
        category_id: Optional[int] = None,
        description: str = None,
        trx_date: date = None
    ) -> TrsTransaction: ...

    async def create_debt(
        self,
        creditor_user_id: int,
        debtor_user_id: int,
        amount: float,
        description: str,
        notes: Optional[str] = None
    ) -> TrsDebt: ...

    async def get_debts_owed(self, user_id: int, status: str = "pending") -> List[TrsDebt]: ...
    async def get_debts_to_collect(self, user_id: int, status: str = "pending") -> List[TrsDebt]: ...
    async def get_debt_by_id(self, debt_id: int) -> Optional[TrsDebt]: ...
    async def mark_debt_as_paid(self, debt_id: int, transaction_id: Optional[int] = None) -> TrsDebt: ...
    async def cancel_debt(self, debt_id: int) -> TrsDebt: ...

    async def get_latest_open_debt_between(
        self,
        creditor_user_id: int,
        debtor_user_id: int
    ) -> Optional[TrsDebt]: ...
